name: GitHub Pages

on:
  push:
    branches:
      - photophobia
  repository_dispatch:
    types: [hugo-deploy]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hugo repo
        uses: actions/checkout@v4
      
      - name: Clone posts repo
        run: |
          git clone https://github.com/huoxj/blog-docs.git blog-docs
      
      - name: Install python deps
        run: |
          pip install frontmatter
        
      - name: Process posts
        run: |
          cd blog-docs
          python process.py
          cp -r posts ../content/
  
  build:
    runs-on: ubuntu-latest
    needs: prepare-posts
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.135.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4